---
language: python
services: docker

env:
  global:
    - ROLE_NAME: cuda
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04
#    - MOLECULE_DISTRO: ubuntu/bionic64 
#    - MOLECULE_DISTRO: ubuntu/xenial64 
#    - MOLECULE_DISTRO: generic/centos7
install:
  # Install test dependencies.
  - pip install molecule docker
script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
