- include_tasks: "install_host/{{ ansible_os_family }}.yml"

- name: blacklist the nouveau driver module
  kernel_blacklist:
    name: nouveau
    state: present

- name: install cuda-drivers (needed for runtime)
  package:
    name: cuda-drivers
    state: present

- name: verify drivers are working
  block:
    - name: reboot the system
      reboot:
        post_reboot_delay: 30
    - name: check if nvidia drivers are working  # noqa 301
      command: nvidia-smi
  when: inventory_hostname != "localhost"
