- include_tasks: "install_host/{{ ansible_os_family }}.yml"

- name: blacklist the nouveau driver module
  kernel_blacklist:
    name: nouveau
    state: present

- name: install cuda-drivers (needed for runtime)
  package:
    name: cuda-drivers
    state: present
  notify:
    - system_restart

- name: check if nvidia drivers are working  # noqa 301
  command: nvidia-smi
