- name: ensure utilities are installed
  package:
    name:
      - pciutils

- name: check if gpu exists # noqa 301
  shell: "lspci | grep NVIDIA"
  register: havegpu
  ignore_errors: true

- name: check that we are not in a docker
  stat:
    path: /.dockerenv
  register: docker

- include_tasks: "cuda.yml"
  when: not docker.stat.exists and havegpu is success
