- name: check if nvidia drivers are working
  register: gpu_working
  shell: nvidia-smi && ls /usr/local | grep $(echo {{ cuda_version }} | tr '-' '.')
  ignore_errors: true

- include_tasks: "cuda/{{ ansible_facts['distribution'] }}.yml"
  when: gpu_working is failed

- name: install cuda-drivers (needed for runtime)
  package:
    name: cuda-drivers
    state: present

# - name: install cuda-development (needed for developing)
# package:
# name: cuda-minimal-build
# state: present

- name: blacklist the nouveau driver module
  kernel_blacklist:
    name: nouveau
    state: present

- reboot:
  when: gpu_working is failed

- name: check if nvidia drivers are working
  command: nvidia-smi
  when: gpu_working is failed
