- name: enable cuda repository
  copy:
    dest: /etc/yum.repos.d/cuda.repo
    content: |
      [cuda]
      name=cuda
      baseurl=http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub
