- name: Enable cuda repository
  copy:
    dest: /etc/yum.repos.d/cuda.repo
    content: |
      [cuda]
      name=cuda
      baseurl=http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub

# Must have latest CentOS Kernel to use kernel-devel
- name: Install latest kernel # noqa 403
  yum:
    name:
      - kernel
    update_cache: yes
    state: latest

- name: Install kernel pre-reqs
  yum:
    name:
      - epel-release
      - dkms
      - kernel-devel
    state: installed
