---
- name: Get public key for repo verification
  apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }}/7fa2af80.pub"
    id: 7fa2af80
    state: present

- name: Add nvidia cuda repository
  apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: cuda
  register: nvidia_repo_cuda_apt_repo

- name: Update cache with new cuda repo
  apt:
    update_cache: yes
